### ISSUE TITLE
[feat]Airdrop Module

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai_shang_nft_gallery#3]
`money`: `500 R` + `200R(for Admin Modules and Page)`

fields: 

- `id`(default)
- `description`: string
- `related_link`: string
- `sum`: integer
- `paid_for`: list --- 
```
[
   %{
      addr: "0x73c7448760517E3E6e416b2c130E3c6dB2026A1d",
      money: 5,
      unit: "usdc"
   },
   ……
]
```
- `tx_ids`: list --- `[tx_id1, tx_id2]`
- `chain_id`: integer
- `timestamps`

<img width="916" alt="image" src="https://user-images.githubusercontent.com/12784118/160778018-aabef454-8eec-427c-813e-7efda4d05bd1.png">

It should be show as `items` @ the bottom of gallery.

```
+------------------+
| column names       |
| item a            |
| item b            |
| item c          |
+------------------+
```

**Comment by kenspirit** [comment]
试一下

**Comment by gofenix** [comment]
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/6822558/160841601-77ca63b3-1de8-4ea4-b128-1f23c69c56c7.png">

尝试了一下，是在这个地方加么

**Comment by kenspirit** [comment]
@zhenfeng-zhu 你在弄我就不弄了。

需要一个chain_id，和chain这个表关联，以让tx_id在页面上显示的时候是一个指向浏览器的link

加到最下面，整个页面的bottom处。paid_for 是 PG 里面的 array of json

**Comment by kenspirit** [comment]
可以再添加管理员登录，添加 airdrop 信息的功能。可以参考用 Pow 的例子：

https://github.com/WeLightProject/Tai-Shang-Voxel-Handler/tree/57e0e6be1f9d422fc9cb4a86a6f1747659e5f178/backend/voxel_handler

**Comment by leeduckgo** [comment]
> 可以再添加管理员登录，添加 airdrop 信息的功能。可以参考用 Pow 的例子：
> 
> https://github.com/WeLightProject/Tai-Shang-Voxel-Handler/tree/57e0e6be1f9d422fc9cb4a86a6f1747659e5f178/backend/voxel_handler

对👍也可以采用自己习惯的鉴权的方式。

这个功能paid additional 吧：

`200 R`

**Comment by gofenix** [comment]
> @zhenfeng-zhu 你在弄我就不弄了。
> 
> 
> 
> 需要一个chain_id，和chain这个表关联，以让tx_id在页面上显示的时候是一个指向浏览器的link
> 
> 
> 
> 加到最下面，整个页面的bottom处。paid_for 是 PG 里面的 array of json

没事，你来搞吧，我是学习一下liveview，到时候看看你是咋做的，我现在是小白

**Comment by kenspirit** [comment]
@zhenfeng-zhu 我才是 Elixir 小白 😄

**Comment by leeduckgo** [comment]
Add Manager Page & Link in Home Page when Login to all the pages that need login
