### ISSUE TITLE
[bug-fix] Meet 403 error when using HTTPPoison to access https://api-moonbeam.moonscan.io/api

### ISSUE THREAD

**Issue by kenspirit** [WeLightProject/tai_shang_nft_gallery#6]
我在 Elixir 中用：

HTTPoison.get!("https://api-moonbeam.moonscan.io/api?module=account&action=txlist&address=0x34Ef2EAeA4E7b8F6e8D629b2AdaEe8d1Fb641655&startblock=0&endblock=733885&sort=asc&apikey=")

的话就会 403。

但直接

curl https://api-moonbeam.moonscan.io/api?module=account&action=txlist&address=0x34Ef2EAeA4E7b8F6e8D629b2AdaEe8d1Fb641655&startblock=0&endblock=733885&sort=asc&apikey=

就可以

**Comment by kenspirit** [comment]
Add User-Agent should fix the issue

**Comment by leeduckgo** [comment]
Money: `200R`
